my_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('code/resume', views.resume, name = 'resume'),
    path('code/projects', views.projects, name= 'projects'),
    path('art-<slug:slug>', views.gallery, name = 'gallery'),
]

portfolio/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.text import slugify

from colorfield.fields import ColorField

class ResumeItem(models.Model):
    title = models.CharField(max_length=256)
    company = models.CharField(max_length=256)
    start_date = models.DateField()
    # Null iff currently employed there
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

class Bullet(models.Model):
    """
    Bullet point for a resume
    """
    text = models.TextField()
    item = models.ForeignKey(ResumeItem, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class CodingProject(models.Model):
    """
    Details of a coding project
    """
    title = models.CharField(max_length=256)
    tagline = models.CharField(max_length=256)
    technologies = models.TextField()
    project_link = models.CharField(max_length=256)
    project_link_display_text = models.CharField(max_length=256)
    text = models.TextField()
    
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title

class Gallery(models.Model):
    """
    A gallery with images, gifs, movie files
    """
    title = models.CharField(max_length=256)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['title']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Gallery, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class Media(models.Model):
    """
    An image, gif to be displayed in a Post or a Gallery
    """
    media = models.ImageField(upload_to="images")
    alttext = models.CharField(max_length=256)

    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, null=True)
    coding_project = models.ForeignKey(CodingProject, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.alttext

class Embed(models.Model):
    """
    Src for an embedded video
    """
    src = models.CharField(max_length=256)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)

    def __str__(self):
        return self.src

portfolio/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse

from django.urls import reverse
from django.views import generic

from .models import Gallery, ResumeItem, CodingProject, Media

def index(request):
    context = {}
    return render(request, 'portfolio/index.html', context)

def resume(request):
    item_list = ResumeItem.objects.order_by('start_date').reverse()
    context = {
        'item_list': item_list,
    }
    return render(request, 'portfolio/resume.html', context)

def projects(request):
    project_list = CodingProject.objects.all()
    context = {
        'project_list': project_list,
    }
    return render(request, 'portfolio/projects.html', context)

def gallery(request, slug):
    # Load gallery that will be displayed
    gallery = get_object_or_404(Gallery, slug=slug)
    # Load other galleries as well for navigation display
    gallery_list = Gallery.objects.all()
    context = {
        'gallery': gallery,
        'gallery_list': gallery_list,
    }
    return render(request, 'portfolio/gallery.html', context)

portfolio/templates/portfolio/footer.html
<footer class="footer bg-light" style="margin-top:16px;padding-bottom:16px;padding-top:16px;">
    <div class="row justify-content-center">
        <h4>Contact</h4><br>
    </div>
    <div class="row justify-content-center">
        <p class="text-center">
            alberse.john@gmail.com <br>
            Resume available on request
        </p>
    </div>
    <div class="row justify-content-center">
        <a class="btn btn-social-icon btn-twitter" href="https://twitter.com/JohnAlberse">
            <span class="fab fa-twitter"></span>
        </a>
        <a class="btn btn-social-icon btn-instagram" href="https://www.instagram.com/johnalberseart/">
            <span class="fab fa-instagram"></span>
        </a>
        <a class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com/in/john-alberse-518453172/">
            <span class="fab fa-linkedin"></span>
        </a>
        <a class="btn btn-social-icon btn-github" href="https://github.com/jalberse">
            <span class="fab fa-github"></span>
        </a>
    </div>
</footer>

portfolio/templates/portfolio/gallery.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% include "portfolio/global-head.html" %}
    <!-- Page css -->
    <link rel="stylesheet" href="{% static 'portfolio/css/gallery.css' %}">

    <title>{{ gallery.title }}</title>
  </head>
  <body>
    <!-- Global navbar -->
    {% include "portfolio/navbar.html" %}
    <!-- Art category navigation -->
    <!-- For an arbitrary number of art categories -->
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <ul class="navbar-nav">
        {% for gal in gallery_list %}
          {% if gal.id == gallery.id %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'portfolio:gallery' gal.slug %}">{{gal.title}}</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:gallery' gal.slug %}">{{gal.title}}</a>
          </li>
          {% endif %}
        {% endfor %}
      </ul>
    </nav>
    <div class="container-fluid">
      <!-- Gallery Information -->
      <div class="row justify-content-center pt-1">
        <h1>
          {{ gallery.title }}
        </h1>
      </div>
      <!-- Any vimeo videos -->
      <div class="row justify-content-center mb-3">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
          {% for embed in gallery.embed_set.all %}
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" src="{{ embed.src }}" allowfullscreen></iframe>
            </div>
          {% endfor %}
        </div>
        <div class="col-sm-2"></div>
      </div>
      <!-- The gallery -->
      <div class="row">
        <div class="col-sm-4">
          {% for media in gallery.media_set.all %}
            {% if forloop.counter0|divisibleby:3 %}
              <img class="img-fluid mb-1" src="{{ media.media.url }}" alt="{{ media.alttext }}">
            {% endif %}
          {% endfor %}
        </div>
        <div class="col-sm-4">
          {% for media in gallery.media_set.all %}
            {% if forloop.counter0|add:2|divisibleby:3 %}
              <img class="img-fluid mb-1" src="{{ media.media.url }}" alt="{{ media.alttext }}">
            {% endif %}
          {% endfor %}
        </div>
        <div class="col-sm-4">
          {% for media in gallery.media_set.all %}
            {% if forloop.counter0|add:1|divisibleby:3 %}
                <img class="img-fluid mb-1" src="{{ media.media.url }}" alt="{{ media.alttext }}">
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
    
    {% include "portfolio/footer.html" %}

    <!-- Bootstrap javascript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/global-head.html
{% load static %}
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- font awesome -->
<script src="https://kit.fontawesome.com/a519d8798e.js"></script>
<!-- Project CSS -->
<link rel="stylesheet" href="{% static 'portfolio/css/portfolio.css' %}">
<link rel="stylesheet" href="{% static 'portfolio/css/bootstrap-social.css' %}">

portfolio/templates/portfolio/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% include "portfolio/global-head.html" %}
    <title>Home</title>
  </head>
  <body>
    <!-- Global navbar -->
    {% include "portfolio/navbar.html" %}
    
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4 offset-md-4">
          <div class="text-center">
            <img class="img-fluid rounded-circle" style="padding:16px;" src="{% static 'img/me.jpg' %}">
          </div>
          <p class="text-center">
              John Alberse is an illustrator and programmer based out of Kansas City. 
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2 offset-md-4">
          <a href="{% url 'portfolio:gallery' slug='animation' %}" class="btn btn-light btn-block" role="button">Art</a>
        </div>
        <div class="col-md-2">
          <a href="{% url 'portfolio:projects' %}" class="btn btn-dark btn-block" role="button">Code</a>
        </div>
      </div>
    </div>

    {% include "portfolio/footer.html" %}

    <!-- Bootstrap javascript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'portfolio:index' %}">John Alberse</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link float-right" href="{% url 'portfolio:index' %}">Home<span class="sr-only">(current)</span></a>
      <a class="nav-link float-right" href="{% url 'portfolio:projects' %}">Code</a>
      <a class="nav-link float-right" href="{% url 'portfolio:gallery' slug='animation' %}">Art</a>
      <a class="nav-link float-right" href="https://github.com/jalberse">GitHub</a>
      <a class="nav-link float-right" href="https://www.inprnt.com/gallery/jra1152/">Store</a>
    </div>
  </div>
</nav>

portfolio/templates/portfolio/projects.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% include "portfolio/global-head.html" %}
    <title>Code</title>
  </head>
  <body>
    <!-- Global navbar -->
    {% include "portfolio/navbar.html" %}
    <!-- Section navigation -->
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'portfolio:projects' %}">Projects</a>
        </li>
      </ul>
    </nav>
    <!-- Entries -->
    <div class="container-fluid">
      {% for project in project_list %}
        <div class="row {% cycle 'row-even' 'row-odd' %}">
          <!-- Text 3/8 of center -->
          <div class="col-lg-5 offset-lg-1">
            <div class="text-right">
              <h3> {{ project.title }} </h3>
              <h4 class="font-weight-light"> {{ project.tagline }} </h4>
              <a href="{{ project.project_link }}" style="margin:4px;" class="btn btn-dark" role="button">{{ project.project_link_display_text }}</a>
              <br>
            </div>
            <p>
              {{ project.text|linebreaks }}
            </p>
            <div class="text-right">
              <h5 class="font-weight-light">
                Technology
              </h5>
              <p>
                {{ project.technologies|linebreaks }}
              </p>
            </div>
          </div>
          <!-- Image 5/8 of center -->
          <div class="col-lg-5 align-self-center text-center">
            {% for media in project.media_set.all %}
              <img class="img-fluid" style="width:500px;" src="{{ media.media.url }}" alt="{{ media.alttext }}">
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
    
    {% include "portfolio/footer.html" %}
    
    <!-- Bootstrap javascript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/resume.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    {% include "portfolio/global-head.html" %}
    <title>Code</title>
  </head>
  <body>
    <!-- Global navbar -->
    {% include "portfolio/navbar.html" %}
    <!-- Section navigation -->
    <!-- Entries -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          {% for item in item_list %}
            <h3>{{ item.company }}</h3>
            {% if item.end_date %}
              <h4 class="font-weight-light">{{ item.title }} | {{ item.start_date|date:"M Y" }} - {{ item.end_date|date:"M Y"}}</h4>
            {% else %}
              <h4 class="font-weight-light">{{ item.title }} | {{ item.start_date|date:"M Y"}}</h4>
            {% endif %}
            <ul>
              {% for bullet in item.bullet_set.all %}
                <li>
                  {{ bullet }}
                </li>
              {% endfor %}
            </ul>
          {% endfor %}
        </div>
      </div>
    </div>  

    {% include "portfolio/footer.html" %}
    
    <!-- Bootstrap javascript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>